<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net4.8</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="0Harmony">
        <HintPath>.lib\0Harmony.dll</HintPath>
      </Reference>
      <Reference Include="BepInEx">
        <HintPath>.lib\BepInEx.dll</HintPath>
      </Reference>
      <Reference Include="BepInEx.Harmony">
        <HintPath>.lib\BepInEx.Harmony.dll</HintPath>
      </Reference>
      <Reference Include="UnderMine">
        <HintPath>.lib\UnderMine.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine">
        <HintPath>.lib\UnityEngine.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CoreModule">
        <HintPath>.lib\UnityEngine.CoreModule.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
